### ISSUE TITLE
Doesnt Work

### ISSUE THREAD

**Issue by DurozIsTaken** [HalfloveJAR/DailyRewards2-Docs#1]
The problem is that the plugin won't work with my 1.20.2 paper server
It says Internal Error has occured. I purchased this plugin from spigot and
and put it in the plugins folder and restarted the server. I joined back and did the command to start but it said internal error. I did /plugins and the plugin was red. I downloaded version 2.0. Please help me resolve this issue

**Comment by HalfloveJAR** [comment]
Hey I wrote the plugin for 1.20.4, so this should be an easy fix

**Comment by HalfloveJAR** [comment]
Hey, sorry for the inconvenience, I went ahead a released a new version with support for 1.20, 1.20.1, 1.20.2 and 1.20.4. There are some other changes as well since the first release that may be helpful to you as well. Check it out here: https://www.spigotmc.org/resources/daily-rewards-2.115112/updates

Thanks!

**Comment by DurozIsTaken** [comment]
Thank you so much I was devastated after I spent 2 dollars and it didn't work

**Comment by DurozIsTaken** [comment]
We added the new version but it still wouldn't work. Same server, Same issue.  We downloaded the correct version but it still seems not to work on the papermc 1.20.2 server please let me know if there is a fix. If not I would like a refund

**Comment by HalfloveJAR** [comment]
> We added the new version but it still wouldn't work. Same server, Same issue. We downloaded the correct version but it still seems not to work on the papermc 1.20.2 server please let me know if there is a fix. If not I would like a refund

Can you send me the console log when you try to boot up? It might be something else, I just tested it again on a 1.20.2 paper server and it worked no problem on my end weirdly

**Comment by HalfloveJAR** [comment]
![2024-02-25_07-32-16_MAbIx2BCTX](https://github.com/HalfloveJAR/DailyRewards2-Docs/assets/29326375/aebc2adb-bfc5-4896-be9c-53f1f2826e86)

**Comment by HalfloveJAR** [comment]
Make sure to delete the old DailyRewards-2.0.jar file from your plugin folder if you haven't already 👍

**Comment by DurozIsTaken** [comment]
Yes we did delete the old file here is the console picture

![image](https://github.com/HalfloveJAR/DailyRewards2-Docs/assets/161179735/2e8b2411-51b8-43f5-81c0-5e1a17e4f4c3)

**Comment by DurozIsTaken** [comment]
Sorry that was the wrong screenshot of a different version heres the right screenshot

![image](https://github.com/HalfloveJAR/DailyRewards2-Docs/assets/161179735/6530d527-d634-4d88-ad21-40fb4ff21cdc)

**Comment by HalfloveJAR** [comment]
Ok let me see what I can do about this, thanks for the screenshots

**Comment by HalfloveJAR** [comment]
I figured out the problem, since most of my plugin is written in Kotlin, I need to compile Kotlin into the jar file since not everyone (as is this case) has Kotlin installed on their machine locally. The only downside is the jar file is a lot bigger now, but its still less than 2.5mb.

I'll post another update for this now, just got it working :D

**Comment by HalfloveJAR** [comment]
Fixed now in the latest patch, thanks for the report and your patience! https://www.spigotmc.org/resources/daily-rewards-2.115112/updates

**Comment by DurozIsTaken** [comment]
Thank you!
